# .github/FUNDING.yml

github: KeaganGilmore
custom:
  - https://www.paypal.com/paypalme/KeaganGilmore15?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000269&utm_unptid=c98f4490-8868-11ee-9291-3cecef432c93&ppid=RT000269&cnac=ZA&rsta=en_US%28en-ZA%29&cust=2C5VJWAXPHY9E&unptid=c98f4490-8868-11ee-9291-3cecef432c93&calc=f751073bfeade&unp_tpcid=ppme-social-user-profile-created&page=main%3Aemail%3ART000269&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.216.0&xt=104038%2C127632
